# Generated by Django 5.1.1 on 2024-09-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habilidad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre de Habilidad')),
                ('nivel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['habilidad'],
            },
        ),
    ]
