# Generated by Django 3.2 on 2024-10-29 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appportfolio', '0007_auto_20241024_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevistador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Avatar')),
                ('empresa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Empresa')),
                ('fecha_entrevista', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrevista')),
                ('conectado', models.BooleanField(blank=True, null=True, verbose_name='Conectado')),
                ('seleccionado', models.BooleanField(blank=True, null=True, verbose_name='Seleccionado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrevistados_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrevistador',
                'verbose_name_plural': 'Entrevistadores',
                'ordering': ['empresa'],
            },
        ),
    ]
