# Generated by Django 4.1.5 on 2024-11-07 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appportfolio', '0010_alter_imagen_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistador',
            name='fecha_entrevista',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Entrevista'),
        ),
        migrations.AlterField(
            model_name='entrevistador',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrevistados_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
