# Generated by Django 4.1.5 on 2024-11-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0011_alter_entrevistador_fecha_entrevista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre')),
                ('apellido1', models.CharField(blank=True, max_length=25, null=True, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo apellido')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCurriculumExperiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_curriculum_experiencia', to='appportfolio.curriculum')),
                ('experiencias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_experiencias', to='appportfolio.experiencia')),
            ],
            options={
                'verbose_name': 'Detalle curriculum experiencia',
                'verbose_name_plural': 'Detalle curriculum experiencias',
                'ordering': ['experiencias'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCurriculumEstudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_curriculum_estudio', to='appportfolio.curriculum')),
                ('estudios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_estudios', to='appportfolio.estudio')),
            ],
            options={
                'verbose_name': 'Detalle curriculum estudio',
                'verbose_name_plural': 'Detalle curriculum estudios',
                'ordering': ['estudios'],
            },
        ),
    ]
