# Generated by Django 4.1.5 on 2024-11-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0015_estado_tareas_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
